#Dictionary containing public configurations
#Change as needed
config = {
	'screensize' : (800,600) , 
	'timer_constant' : 100 ,
	'bottom_line' : 600 , 

}

MOVE_VAL = 50
LINE_COORDINATES = [(0,600),(800,600)]

#Dictionary containing private configurations
#Don't touch!
privateConfig = {
	'square_size' : 50 ,
	'max_screen_right' : 650 ,
	'max_screen_left' : 50 ,
	'max_screen_top' : 0,
	'max_screen_bottom' : 600
}

#Dictionary containing RGB tuples of some colorss
colors = {
	'RED' : (255,0,0) ,
	'GREEN' : (0,255,0) ,
	'BLUE' : (0,0,255) , 
	'BLACK' : (0,0,0) ,
	'WHITE' : (255,255,255)
}

#Dictionary containing the index of the corresponding destination piece generated by a rotation
rotations = {
	0 : 5 ,
	1 : 6 ,
	2 : 9 ,
	3 : 10 ,
	4 : 4 ,
	5 : 0 , 
	6 : 7 ,
	7 : 8 ,
	8 : 1 ,
	9 : 2 ,
	10 : 11 ,
	11 : 12 ,
	12 : 3
}
